#! /bin/sh
### mqtt2redis_check.sh
# Ho creato questo script per controllare che mqtt2redis_d.py
# rimanga in esecuzione, anche in caso di errore/i di
# programmazione che blocca/no il programma insapettatamente.
### END INFO

#DIR=/var/www/cgi-bin
#DAEMON=$DIR/mqtt2redis_d.py
DAEMON_NAME=mqtt2redis_d


PID=`ps -e -o pid,cmd | grep "$DAEMON_NAME[.]py" | awk '{ print $1 }'`
if [ "$PID" != "" ]
    then
        echo "$DAEMON_NAME is running!"
        echo "Pid is: $PID"
    else
        echo "$DAEMON_NAME not running!"
        redis-cli -h centred hmset msg:redis:alive:$(date +\%Y\%m\%d\%H\%M\%S) type "alert" desc "mqtt2redis_d.py (level1) in errore, tentativo di riavvio demone" value "off" um "" date "$(date +\%Y/\%m/\%d\ \%H:\%M:\%S)" > /dev/null
        su -c "/var/www/cgi-bin/mqtt2redis_init.d.sh restart" pi
fi

